### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by massivespace** [AxeQiu/SimpleExchangeProxyServer#1]
Could you update the wiki or README with a short description of how to use this project?  A simple example would be fine too.  I think this proxy server is exactly what I've been looking for, but I have no clue how to utilize it.  Thanks!

**Comment by AxeQiu** [comment]
Hi, at my place the github.com access much slower so I don't usually come so ignore your message, sorry.  I have updated my README and offered an example on here. Hoping can help you!
